//
//  RankedAppListViewController.swift
//  AppStore
//
//  Created Sang Tae Kim on 2017. 3. 22..
//  Copyright © 2017년 haibane. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class RankedAppListViewController: UIViewController {

    @IBOutlet fileprivate weak var rankedAppListCollectionView: UICollectionView!
    fileprivate var rankedAppList: [RankedAppType]?
    override func viewDidLoad() {
        super.viewDidLoad()
        rankedAppListCollectionView.register(UINib(nibName: "RankedAppCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "RankedAppCell")
        
        RankedAppListDataService().fetchRankedAppList { [weak self] (rankedAppList: [RankedAppType]?) in
            self?.rankedAppList = rankedAppList
            self?.rankedAppListCollectionView?.reloadData()
        }
    }

}

extension RankedAppListViewController: UICollectionViewDelegate {
    
}

extension RankedAppListViewController: UICollectionViewDataSource {
    public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return rankedAppList?.count ?? 0
    }
    
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "RankedAppCell", for: indexPath) as! RankedAppCollectionViewCell
        if var rankedApp = rankedAppList?[indexPath.row] {
            rankedApp.rank = indexPath.row + 1
            cell.configure(with: rankedApp)
        }
        return cell
    }

}

extension RankedAppListViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: UIScreen.main.bounds.width, height: 80)
    }

}
