//
//  AppListViewController.swift
//  AppStore
//
//  Created Sang Tae Kim on 2017. 3. 22..
//  Copyright © 2017년 haibane. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class AppListViewController: UIViewController, AppListViewProtocol {
    
    lazy var appListViewPresenter: AppListViewPresenterProtocol? = AppListViewPresenter()
    fileprivate var appList: [AppType]?
    @IBOutlet fileprivate weak var tableView: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()
        appListViewPresenter?.appListView = self
        appListViewPresenter?.viewDidLoad()
        configureTableView()
    }
    
    private func configureTableView() {
        tableView.estimatedRowHeight = 60
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.tableFooterView = UIView()
        tableView.register(UINib(nibName: "AppTableViewCell", bundle: nil), forCellReuseIdentifier: "AppTableViewCell")
    }
    
    func show(from appList:[AppType]?) {
        self.appList = appList
        tableView?.reloadData()
    }

}

extension AppListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: false)
        appListViewPresenter?.didSelect(appList?.item(at: indexPath.row))
    }
}

extension AppListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return appList?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "AppTableViewCell", for: indexPath) as! AppTableViewCell
        if var appData = appList?.item(at: indexPath.row) {
            appData.index = indexPath.row + 1
            cell.configure(with: appData)
        }
        return cell
    }
}

